version: '3'

services:
  auth-db:
    container_name: auth_db
    image: postgres:16.2
    restart: always
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - '${DB_PORT_EXT:-5432}:5432'
    environment:
      - POSTGRES_USER=${DB_USERNAME:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-1234567}
      - POSTGRES_DB=${DB_NAME:-authdb}

  auth-ms:
    container_name: auth_ms_prod
    build:
      context: .
      dockerfile: dockerfile.prod
    restart: always
    depends_on:
      - auth-db
    environment:
      - DB_HOST=auth-db
      - DB_PORT=5432
      - DB_USERNAME=${DB_USERNAME:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-1234567}
      - DB_NAME=${DB_NAME:-authdb}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION:-1h}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - UPLOAD_IMAGE_SERVICE_URL=${UPLOAD_IMAGE_SERVICE_URL}
